### ISSUE TITLE
Fix typo

### ISSUE THREAD

**Issue by simonbingham** [JIAZHEN/releasehub#2]
"Summanry" should be "Summary".

![screen shot 2016-03-21 at 11 00 16](https://cloud.githubusercontent.com/assets/1306644/13916711/22ce09e4-ef54-11e5-9271-987c8751a931.png)

**Comment by JIAZHEN** [comment]
:+1:  Will fix it

**Comment by JIAZHEN** [comment]
Fixed in 9e7b2b11d885f4a6fcc930085ae850ef71c8726a
