### ISSUE TITLE
Order branch list dropdown alphabetically

### ISSUE THREAD

**Issue by simonbingham** [JIAZHEN/releasehub#5]
For repositories that have lots of branches (you know the one I'm referring to) would it be possible to order the branch list dropdown alphabetically? Currently it can take a lot of time to find the branch being deployed.

**Comment by JIAZHEN** [comment]
I will look into that. Thanks @simonbingham

**Comment by JIAZHEN** [comment]
It seems like the branch is ordered by alphabetically. @simonbingham could you please double check?

**Comment by simonbingham** [comment]
It is Joe. I'm sure it wasn't the last time a checked. Weird! 👍
