### ISSUE TITLE
Clicking "Sync Branch List" should not lose selected branch

### ISSUE THREAD

**Issue by mendable** [JIAZHEN/releasehub#9]
Clicking `Sync Branch List` causes the selected branch to be changed, which can cause the wrong branches to be submitted in Release Requests often if people forget to change them. I think users intentions in a lot of cases is just quickly refreshing the SHA to make sure they have the latest.

Ideally, clicking Sync Branch List would:
- Keep the branch you had previously selected.
- Unless the branch had been deleted, in which case selecting an "empty" branch option by default.
  - A validation on RR submit would not allow the RR to be submitted if no branch was selected.

**Comment by JIAZHEN** [comment]
Fixed in 9784e771823710e7563b3313d320420b9cbb829f
